### ISSUE TITLE
Expecting property name enclosed in double quotes: line 2 column 2 (char 3)

### ISSUE THREAD

**Issue by ShrineFox** [hazimavdal/gpurge#1]
After each .gdoc or .gsheet file, I'm getting this error:
`Error processing "C:\Users\Ryan\Documents\Google Drive\amicitia.gsheet": Expecting property name enclosed in double quotes: line 2 column 2 (char 3)`

I successfully authenticated myself, but it seems I'm stuck here.
For reference, here's my input:
`python gpurge.py -f "C:\Users\Ryan\Documents\Google Drive" -r -v 1`

If it matters, here's what the contents of the .gsheet/.gdoc files looks like for me:
```
{
	// WARNING! DO NOT EDIT THIS FILE! ANY CHANGES MADE WILL BE LOST!
	"doc_id" : "<doc id>",
	"email" : "<my email>",
	"resource_key" : "",
	"url" : "<doc url>"
}
```

**Comment by hazimavdal** [comment]
It is because of the comment in the JSON file as the script is not able to parse it as valid JSON (JSON does not support comments). I'm not sure why it has the comment, I checked my Drive files and none of them has a comment. Regardless, I will push a workaround soon. 

Thank you for using the script and opening this issue.

**Comment by hazimavdal** [comment]
I pushed a fix for your particular use case.
